# @package _global_
hydra:
  launcher:
    cpus_per_task: 40
    gpus_per_node: 1
    tasks_per_node: 1
    timeout_min: 600
    mem_gb: 64
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  sweep:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}