# @package _global_
hydra:
  launcher:
    partition: learnfair
    cpus_per_task: 16
    gpus_per_node: 1
    tasks_per_node: 1
    timeout_min: 90
    mem_gb: 32
    name: ${hydra.job.name}
    array_parallelism: 256
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  run:
    dir: /checkpoint/${env:USER}/outputs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  sweep:
    dir: /checkpoint/${env:USER}/outputs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}